//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeminarskaNalogaIvanov.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Dijak> Dijaks { get; set; }
        public virtual DbSet<DijakPodročje> DijakPodročje { get; set; }
        public virtual DbSet<Izvedba> Izvedbas { get; set; }
        public virtual DbSet<IzvedbaDijak> IzvedbaDijaks { get; set; }
        public virtual DbSet<IzvedbaMentor> IzvedbaMentors { get; set; }
        public virtual DbSet<Mentor> Mentors { get; set; }
        public virtual DbSet<PlanDejavnosti> PlanDejavnostis { get; set; }
        public virtual DbSet<PlanDijak> PlanDijaks { get; set; }
        public virtual DbSet<PlanSodelavci> PlanSodelavcis { get; set; }
        public virtual DbSet<Področja> Področja { get; set; }
        public virtual DbSet<Razredniki> Razrednikis { get; set; }
        public virtual DbSet<Slike> Slikes { get; set; }
    }
}
